databases:
  - name: bookstore_db

services:
  - type: web
    name: bookstore-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString
